### ISSUE TITLE
Question on usage

### ISSUE THREAD

**Issue by MeestorX** [kpreisser/TcpTunnel#1]
Love what you've done here. 
Been using nGrok to do TCP tunnelling for a while. With nGrok, I run the app on the remote computer, and locally I only need a url:port to access that computer, no application required locally. (Of course nGrok is the gateway)
Is this functionality possible with your solution, or does it require a client AND server app to be running for it to work?

**Comment by kpreisser** [comment]
Hi @MeestorX,
thanks for opening this issue!

TcpTunnel requires all of the three instances (*gateway*, *proxy-server*, *proxy-client*) to be running for it to work, as this is an "on-premises" application that doesn't use any cloud service. (However, for example the *gateway* and *proxy-server* instances could also be run on the same machine.)

For example, to allow others to access a web server running on a machine behind a firewall/NAT (which seems to be a common use case for nGrok), you could run both the *gateway* and *proxy-server* instances on a public server like a VPS (that is reachable over the internet), and run the *proxy-client* instance on the remote machine (behind NAT/Firewall) where the web server is running.

For this, you could use a configuration file similar like this on the public server (the passwords in the `Session` elements must be replaced with secure ones):
```xml
<Settings xmlns="https://github.com/kpreisser/TcpTunnel">
  <!-- Set-up the gateway instance. -->
  <Instance type="gateway">
    <!-- Use port 25200 with SSL for the connection from the proxy-client. -->
    <Listener port="25200" certificatePemFilePath="my-cert.pem" certificatePemKeyFilePath="my-private-key.pem" />
    <!-- Additionally, use a non-SSL listener for the local connection from the proxy-server. -->
    <Listener port="25201" />
    
    <Session id="1" proxyClientPassword="my_secret_password_client" proxyServerPassword="my_secret_password_server" />
  </Instance>
  
  <!-- Set-up the proxy-server instance that connects to the local gateway.
       This doesn't need to use SSL as it's a local connection, and the gateway listener
       is started before the proxy-server instance is started. -->
  <Instance type="proxy-server" host="localhost" port="25201" useSsl="0">
    <Session id="1" password="my_secret_password_server">
      
      <!-- Listen on port 8080 and forward it to the proxy-client machine on port 8080.-->
      <Binding listenPort="8080" targetHost="localhost" targetPort="8080" />
    </Session>
  </Instance>
</Settings>
```

Additionally, you could use a configuration file like this on the remote machine where the web server is running (where `my-public-server.example.org` represents the domain name where the server is reachable and has a SSL/TLS certificate):
```xml
<Settings xmlns="https://github.com/kpreisser/TcpTunnel">
  <Instance type="proxy-client" host="my-public-server.example.org" port="25200" useSsl="1">
    <Session id="1" password="my_secret_password_client" />
  </Instance>
</Settings>
```

Then, users could open `http://my-public-server.example.org:8080` to access the web server running on the remote machine (behind NAT/Firewall).

**Comment by MeestorX** [comment]
Thank you for your reply. I'll have to give this a try when I get a chance.
Thanks again for your work on this.
