### ISSUE TITLE
Install service script is missing a space following start=

### ISSUE THREAD

**Issue by TalAloni** [kpreisser/TcpTunnel#2]
Hi Konstantin,
Thank you for this terrific project, it works well and is super useful!
One issue I encountered when installing the service:
it should be "start= delayed-auto", not "start=delayed-auto" (there is a space that should be added following the =, similar to binpath= ).
This change was required to install the service on Windows Server 2008 R2 x64.
(the 'sc failure' command did not succeed as well but it wasn't critical for me to figure out why)

**Comment by kpreisser** [comment]
Thanks for opening this issue! You are right, the space character was missing after the `=` in these commands.

However, please note that Windows 7 (SP1) and Windows Server 2008 R2 (SP1) are no longer supported by .NET 7.0 and higher, so the app may not run correctly on these OSes as it uses .NET 8.0.
Thanks!

**Comment by TalAloni** [comment]
Thank you.
.NET 8.0 may not be supported on Windows Server 2008 R2, but I can confirm TcpTunnel works without an issue.
